const ActionTypes = {
    FETCH_QUIZES_START: 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_ERROR: 'FETCH_QUIZES_ERROR',
    FETCH_QUIZ_SUCCESS: 'FETCH_QUIZ_SUCCESS',
};

export default Object.freeze(ActionTypes);